server:
  port: '9220'

management:
  server:
    port: '9228'

metadata:
  node:
    id: '2'
    host: localhost
    port: '9312'
  peers:
    - id: '1'
      host: localhost
      port: '9311'
    - id: '2'
      host: localhost
      port: '9312'
    - id: '3'
      host: localhost
      port: '9313'
  storage-dir: /tmp/raft-server-2

metadata-client:
  client-id: 2e4599e0-d0cd-461d-86e3-01f0206d4736
  group-id: d7d23a0d-26f1-46ce-b10b-af833738907e
  peers:
    - id: '1'
      host: localhost
      port: '9311'
    - id: '2'
      host: localhost
      port: '9312'
    - id: '3'
      host: localhost
      port: '9313'

info:
  app:
    name: 'Key Value State Metadata Server 2'
    version: '1.0'
    description: 'Key Value State Metadata Server 2'