server:
  port: '9230'

management:
  server:
    port: '9238'

metadata:
  node:
    id: '3'
    host: localhost
    port: '9313'
  peers:
    - id: '1'
      host: localhost
      port: '9311'
    - id: '2'
      host: localhost
      port: '9312'
    - id: '3'
      host: localhost
      port: '9313'
  storage-dir: /tmp/raft-server-3

metadata-client:
  client-id: f5805261-720a-4f83-b4c9-8bfd817d9778
  group-id: d7d23a0d-26f1-46ce-b10b-af833738907e
  peers:
    - id: '1'
      host: localhost
      port: '9311'
    - id: '2'
      host: localhost
      port: '9312'
    - id: '3'
      host: localhost
      port: '9313'

info:
  app:
    name: 'Key Value State Metadata Server 3'
    version: '1.0'
    description: 'Key Value State Metadata Server 3'