server:
  port: '9210'

management:
  server:
    port: '9218'

metadata:
  node:
    id: '1'
    host: localhost
    port: '9311'
  peers:
    - id: '1'
      host: localhost
      port: '9311'
    - id: '2'
      host: localhost
      port: '9312'
    - id: '3'
      host: localhost
      port: '9313'
  storage-dir: /tmp/raft-server-1

metadata-client:
  client-id: 0d6d23fc-e7bf-470c-9602-30956393d9ec
  group-id: d7d23a0d-26f1-46ce-b10b-af833738907e
  peers:
    - id: '1'
      host: localhost
      port: '9311'
    - id: '2'
      host: localhost
      port: '9312'
    - id: '3'
      host: localhost
      port: '9313'

info:
  app:
    name: 'Key Value State Metadata Server 1'
    version: '1.0'
    description: 'Key Value State Metadata Server 1'
