package com.bteshome.keyvaluestore.common.requests;

public enum MetadataRequestType {
    TABLE_CREATE,
    TABLE_GET,
    TABLE_LIST,
    METADATA_NODE_LIST,
    STORAGE_NODE_JOIN,
    STORAGE_NODE_LEAVE,
    STORAGE_NODE_GET,
    STORAGE_NODE_LIST,
    STORAGE_NODE_HEARTBEAT,
    STORAGE_NODE_ACTIVATE,
    STORAGE_NODE_DEACTIVATE,
    STORAGE_NODE_METADATA_REFRESH,
    CLIENT_METADATA_REFRESH,
    CONFIGURATION_LIST,
    REPLICA_REMOVE_FROM_ISR,
    REPLICA_ADD_TO_ISR,
    UNKNOWN
}
