{{- define "ds-common.pvc" -}}
{{- if .Values.pvc_enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.serviceName }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc_size }}
  storageClassName: auto-ebs-sc
{{- end }}
{{- end -}}