{{- define "ds-common.service-nodeport" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nodePortServiceName }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.serviceName }}
  type: NodePort
  ports:
    - name: nodeport
      port: {{ .Values.nodePortServicePort }}
      targetPort: {{ .Values.nodePortServicePort }}
      protocol: TCP
{{- end -}}
