server:
  port: '9506'

management:
  server:
    port: '9508'

storage:
  node:
    id: '2'
    host: localhost
    port: ${server.port}
    grpc-port: 9507
    management-port: ${management.server.port}
    rack: ""
    storage-dir: storage-server-2
  grpc-enabled: 'true'

metadata-client:
  client-id: 42af847f-4921-48bb-bec5-fb4898d0a6eb
  group-id: d7d23a0d-26f1-46ce-b10b-af833738907e
  peers:
    - id: '0'
      host: localhost
      port: '9310'
    - id: '1'
      host: localhost
      port: '9311'
    - id: '2'
      host: localhost
      port: '9312'
    - id: '3'
      host: localhost
      port: '9313'

info:
  app:
    name: 'Key Value State Storage Server 2'
    version: '1.0'
    description: 'Key Value State Storage Server 2'